set encoding=utf-8
set fileencoding=utf-8

syntax enable
set number
set ruler
set list
set listchars=tab:>-,trail:.
set nowrap
set showmatch
" set whichwrap=h,l
set nowrapscan
set hidden
set history=2000
set autoindent
set expandtab
set tabstop=4
set shiftwidth=4
set helplang=en
set paste  " a! ペースト時のインデントなし

set whichwrap=b,s,h,l,<,>,[,],~  " 左右のカーソル移動で行を跨いで移動
set mouse=a  " マウス操作を有効にする
set clipboard=unnamed,autoselect
inoremap jj <Esc>  " インサートモードでjjと入力した場合はESCとみなす

set backspace=indent,eol,start  " バックスペースでの削除をいつでも有効にする
set smartindent   " 改行時に入力された行の末尾に合わせて次の行のインデントを増減する

set ignorecase " 大文字小文字を無視
set smartcase  " ignorecaseと合わせることで，小文字入力の時のみ大文字小文字を無視
set incsearch  " インクリメンタルサーチ
set hlsearch   " 検索結果をハイライト
nnoremap <silent> <ESC><ESC> :nohlsearch<CR>  " ESCキー連打でハイライトを消す

set gdefault  " 置換の際のgオプションをデフォルトで有効化する

set foldmethod=marker  " ソースコードを折畳み表示する
" manual: 手動で折畳を定義する
" indent: インデントの数を折畳のレベル(深さ)とする
" expr:   折畳を定義する式を指定する
" syntax: 構文強調により折畳を定義する
" diff:   変更されていないテキストを折畳対象とする
" marker: テキスト中の印で折畳を定義する

set cursorline      " 現在の行をハイライト
hi clear CursorLine " 上と合わせることで行番号のみハイライト

nnoremap Y y$  " 行末までヤンク
set display=lastline  " 一行が長い場合に@を表示しない
set pumheight=10  " 補完メニューの高さ指定
set showmatch  " 括弧のもう片方を0.1秒表示
set matchtime=1

set showcmd  " 入力中のコマンドをステータスに表示する
set nobackup  " バックアップファイルを作らない
set noswapfile  " スワップファイルを作らない
set autoread  " 編集中のファイルが変更されたら自動で読み直す

" 全角スペース・行末のスペース・タブの可視化
if has("syntax")
    syntax on

    " PODバグ対策
    syn sync fromstart

    function! ActivateInvisibleIndicator()
        " 下の行の"　"は全角スペース
        syntax match InvisibleJISX0208Space "　" display containedin=ALL
        highlight InvisibleJISX0208Space term=underline ctermbg=Blue guibg=darkgray gui=underline
        "syntax match InvisibleTrailedSpace "[ \t]\+$" display containedin=ALL
        "highlight InvisibleTrailedSpace term=underline ctermbg=Red guibg=NONE gui=undercurl guisp=darkorange
        "syntax match InvisibleTab "\t" display containedin=ALL
        "highlight InvisibleTab term=underline ctermbg=white gui=undercurl guisp=darkslategray
    endfunction

    augroup invisible
        autocmd! invisible
        autocmd BufNew,BufRead * call ActivateInvisibleIndicator()
    augroup END
endif

" for Kite (AI Autocomplete for Python)
set statusline=%<%f\ %h%m%r%{kite#statusline()}%=%-14.(%l,%c%V%)\ %P
set laststatus=2  " always display the status line

" カレント行ハイライト
set cursorline
" アンダーラインを引く(color terminal)
highlight CursorLine cterm=underline ctermfg=NONE ctermbg=NONE
